language: go
sudo: false

cache:
  directories:
    - $HOME/.glide

go:
  - 1.9.4
  - 1.9.3
  - 1.9.2
  - 1.9.1
  - '1.10'

go_import_path: code.ysitd.cloud/component/account

install:
  - curl -o glide.zip -L https://github.com/Masterminds/glide/releases/download/v0.13.1/glide-v0.13.1-linux-amd64.zip
  - unzip glide.zip && mv linux-amd64/glide $GOPATH/bin/glide && rm -r linux-amd64
  - glide install -v

script:
  - go vet -v
  - go test -v ./...
