language: go
sudo: false

go:
  - 1.9.2
  - 1.9.1
  - 1.9

go_import_path: code.ysitd.cloud/component/account

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.13.1 && go install && cd -
  - glide install -v

script: go test ./...
