version: '2'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    environment:
      DB_URL: "postgresql://postgres:mysecretpassword@postgres:5432/postgres?sslmode=disable"
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:3-alpine
    volumes:
      - ./volumes/redis:/data
  postgres:
    images: postgres:9.6-alpine
    volumes:
      - ./volumes/pgsql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
